#### 类结构

```ascii
					 ┌───────────┐
                     │  Object   │
                     └───────────┘
                           ▲
                           │
                     ┌───────────┐
                     │ Throwable │
                     └───────────┘
                           ▲
                 ┌─────────┴─────────┐
                 │                   │
           ┌───────────┐       ┌───────────┐
           │   Error   │       │ Exception │
           └───────────┘       └───────────┘
                 ▲                   ▲
         ┌───────┘              ┌────┴──────────┐
         │                      │               │
┌─────────────────┐    ┌─────────────────┐┌───────────┐
│OutOfMemoryError │... │RuntimeException ││IOException│...
└─────────────────┘    └─────────────────┘└───────────┘
                                ▲
                    ┌───────────┴─────────────┐
                    │                         │
         ┌─────────────────────┐ ┌─────────────────────────┐
         │NullPointerException │ │IllegalArgumentException │...
         └─────────────────────┘ └─────────────────────────┘
```

##### Error

都属于非 检查异常，即运行时异常

*   OutOfMemortError： 内存耗尽
*   NoClassDefFoundError：无法加载Class
*   StackOverError：栈溢出



##### exception

检查异常：

- SQLException
- IOException



非检查异常：RuntimeException

- IllegalArgumentException
- ArithmeticException



#### 相关操作

##### 检查异常

以IOException为例：

- 方法名后添加 throws IOException ，由调用方处理；
- 方法中添加 try catch 语句处理异常；

自定义时，继承 Exception 即可；



##### 非检查异常

直接抛出非检查异常即可；

自定义时，继承 RuntimeException 



##### 异常捕获

多个catch语句，会从上到下匹配对应的 Exception，匹配到某个catch之后执行catch内代码，然后不再继续匹配；因此Exception子类必须写在前面；



##### finally

- 若无异常，正常执行 try 语句，最后执行 finally；

- 若有异常，不仅执行 try{} catch{} 最后仍要执行 finally；

##### 捕获多个异常

避免在不同的catch块中出现重复的程序处理

##### AutoCloseable

实现函数:

```java
void close() throws Exception
// 实例
public class MyAutoCloseResource implements AutoCloseable{
    public void handle() throws NullPointerException{
        System.out.println("get hashcode: " + this.hashCode());
        throw new NullPointerException("执行时指针异常!");
    }
    @Override
    public void close() throws Exception {
        System.out.println("invoke close()");
        throw new IOException("关闭异常!");
    }
}
static void closeWithException() {
    // 离开try之后,会自动调用 close() 方法
    try (MyAutoCloseResource resource = new MyAutoCloseResource()) {
        resource.handle();
    } catch (NullPointerException nullPointerException) {
        System.out.println("null_pointer message: " + nullPointerException.getMessage());
        nullPointerException.printStackTrace();
    } catch (Exception e) {
        System.out.println("exception message: " + e.getMessage());
        e.printStackTrace();
    }
}
```

##### 抛出异常

```java
public static int parseInt(String s, int radix) throws NumberFormatException {
    if (s == null) {
        throw new NumberFormatException("null");
    }
    ...
}
```

#### 异常处理顺序

结论：

*   无论是否有异常，finally中代码都会执行；
*   当try和catch中有return时候，finally也会执行；
*   当finally中没有return时候，finally是在return语句执行之后、函数返回之前执行；
*   当finally中有return时候，程序将在这里返回；

##### 情景一：try-catch-finally-return

正常顺序执行；

##### 情景二：try(return)-catch-finally-return

1.  执行try中return，但函数不返回；
2.  执行finally；
3.  最后执行try中return返回；

finally之后的return不执行；

##### 情景三：try-catch(return)-finally-return

如果存在异常：

1.  执行catch中return，但函数并不返回；
2.  执行finally；
3.  最后执行catch中return返回，finally后的return不执行；

##### 情景四：try(return)-catch-finally(return)

1.  执行try中return（包括return之后的表达式），但函数不返回；
2.  执行finally， 从finally中的return函数返回；

##### 情景五：try-catch(return)-finally(return)

如果存在异常：

1.  执行catchreturn，但函数不返回；
2.  执行finally，同时函数从此处return返回；

##### 情景六：try(return)-catch(return)-finally(return)

如果存在异常：

1.  执行try中return运算，但是函数并不返回；
2.  执行catch中return运算，但函数并不返回；
3.  执行finally中return运算，函数从此返回；

#### 自定义异常

```ascii
Exception
│
├─ RuntimeException
│  │
│  ├─ NullPointerException
│  │
│  ├─ IndexOutOfBoundsException
│  │
│  ├─ SecurityException
│  │
│  └─ IllegalArgumentException
│     │
│     └─ NumberFormatException
│
├─ IOException
│  │
│  ├─ UnsupportedCharsetException
│  │
│  ├─ FileNotFoundException
│  │
│  └─ SocketException
│
├─ ParseException
│
├─ GeneralSecurityException
│
├─ SQLException
│
└─ TimeoutException
```

常用做法：

1.  自定义 BaseException 作为根异常，一般继承自 RuntimeException
2.  自定义不同异常继承 BaseException；





### 实际应用

- 根据潜在故障机来描述各个用例;
- 解决潜在故障:
  1. 不允许场景出现;
  2. 开发处理器代码:应只针对对程序有重大影响且不可避免的问题和错误;
- 方法仅在以下情况抛出多个异常:
  1. 相互排斥;
  2. 对使用者不同作用;
  3. 表示完全不同的故障;
- 发现问题时,今早处理或者报告,最好作本地处理;



#### 异常类的设计

##### 命名

哪里出了问题来命名,而不是谁丢了异常.

##### 将低层异常转换成高层能理解的异常

第一版使用文件来配置文件:

```java
public void saveProperty() throws IOException
```

第二版使用数据库存储文件:

```java
public void saveProperty() throws SQLException
```

都是将底层实现的异常交由上层，改为丢出PropertyManipulateException，这样不管如何修改，都不会影响丢出的异常，有利于上层调用者的异常处理设计.



##### 同构性异常

设计一个新的异常类型,用这个异常类代表同一类所有函数可能出现的异常.
第一版:

```java
login() throws IOException, SQLException
withdraw() throws IOException, SQLException
deposit() throws IOException, SQLException
```

